migrations:
  - 'Webapp/migrations/**/*'

tests:
  - 'Webapp/tests/**/*'

dependencies:
  - 'pyproject.toml'
  - 'poetry.lock'

CI:
  - '.github/**/*'

need-migrations:
  - 'Webapp/sources/models/**/*'
