name: ai4green-local-dev

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ai4green
      POSTGRES_PASSWORD: postgres

  testdb:
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ai4greentest
      POSTGRES_PASSWORD: postgres

  azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"

  retrosynthesis:
    image: docker.io/ai4greeneln/retrosynthesis:latest
    ports:
      - "8000:8000"

  conditions:
    image: docker.io/ai4greeneln/condition_prediction:latest
    ports:
      - "9901:9901"

  keycloakdb:
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_DB: keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_HOST: keycloakdb
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak_user
      KEYCLOAK_DATABASE_PASSWORD: keycloak_password
    depends_on:
      - keycloakdb


volumes:
  keycloak_data:
    driver: local
