# Configuration settings for the development and dissemination of the ai4green application
# Controls: Databases, Admin, Mail, and, predefined users, workgroups, and workbooks.
---
database_configurations:

      db_postgres:
            provider: 'postgres'
            user: 'postgres'  # default user
            password: ''
            host: ''
            port: '5432'  # default port

      # for the test database. filename changed by assigning value to environmental variable 'DATABASE_URL' 
      db_sqlite:
            provider: 'sqlite'
            filename: 'default'
            create_db: True

compound_limit: 10000 # the number of molecules to take from PubChem

predefined_users:
      admin_user:
            username: ''  # you must define your admin account here
            password: ''
            email: ''
            fullname: ''
            admin: True

mail:
      # use example values in comments to help setup your own mail server if desired
      mail_server: None  # 'smtp.gmail.com'
      mail_port: None  # 465
      mail_username: None  # mail@.com
      mail_password: None  # password
      mail_use_tls: False
      mail_use_ssl: True

marvin_js_api_key: '69b0c6c7851547258e92db7880f174ef'  # add your own Marvin JS API key here
