"""controlled_substances

Revision ID: 0bc125b57d9e
Revises: f5b3539b9a0e
Create Date: 2025-02-11 11:53:25.740289

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0bc125b57d9e"
down_revision = "f5b3539b9a0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controlled_substance_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator", sa.Integer(), nullable=False),
        sa.Column("workgroups", sa.Integer(), nullable=False),
        sa.Column("workbooks", sa.Integer(), nullable=False),
        sa.Column("reactions", sa.Integer(), nullable=False),
        sa.Column("time_of_creation", sa.DateTime(), nullable=True),
        sa.Column("last_edited", sa.DateTime(), nullable=True),
        sa.Column("last_location", sa.Text(), nullable=False),
        sa.Column("controlled_substance_name", sa.Text(), nullable=False),
        sa.Column("controlled_substance_smiles", sa.Text(), nullable=False),
        sa.Column("controlled_substance_cas", sa.Text(), nullable=False),
        sa.Column("controlled_substance_inchi", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["creator"], ["Person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reactions"], ["Reaction.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workbooks"], ["WorkBook.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workgroups"], ["WorkGroup.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("registration_location", sa.JSON(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("most_recent_login_location", sa.JSON(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.drop_column("most_recent_login_location")
        batch_op.drop_column("registration_location")

    op.drop_table("controlled_substance_usage")
    # ### end Alembic commands ###
