"""coshh_template

Revision ID: 13d40f5a5809
Revises: 488aa917bf8c
Create Date: 2026-09-15 16:37:55.039967

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "13d40f5a5809"
down_revision = "488aa917bf8c"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    approval_status_enum = postgresql.ENUM(
        "PENDING",
        "APPROVED",
        "REJECTED",
        "EXPIRED",
        "DRAFT",
        "CHANGES_SUGGESTED",
        name="approvalstatus",
        create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "InputType",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "template_type",
            sa.Enum(
                "COSHH",
                "REACTION",
                "WORKUP",
                "PURIFICATION",
                "RESULTS",
                name="templatetype",
            ),
            nullable=False,
        ),
        sa.Column("time_of_creation", sa.DateTime(), nullable=False),
        sa.Column("time_of_update", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PUBLISHED", "DRAFT", name="templatestatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["creator_id"], ["User.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["Institution.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "COSHHTemplate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["Template.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Section",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["COSHHTemplate.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "TemplateInstance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("reaction_id", sa.Integer(), nullable=False),
        sa.Column(
            "instance_type",
            sa.Enum("GENERIC", "COSHH", name="instancetype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["User.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reaction_id"],
            ["Reaction.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["Template.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "COSHHInstance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("approval_status", approval_status_enum, nullable=False),
        sa.Column("approver_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["User.id"],
        ),
        sa.ForeignKeyConstraint(["id"], ["TemplateInstance.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Field",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("mandatory", sa.Boolean(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("input_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["input_type_id"],
            ["InputType.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["Section.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "FieldResponse",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("template_instance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["Field.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_instance_id"],
            ["TemplateInstance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "SelectFieldOptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["Field.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("time_of_comment", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("field_response_id", sa.Integer(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_response_id"],
            ["FieldResponse.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "FieldResponseValue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("time_of_response", sa.DateTime(), nullable=False),
        sa.Column("field_response_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["field_response_id"],
            ["FieldResponse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Define table structure locally for the migration
    input_type_table = sa.table(
        "InputType",
        sa.column("id", sa.Integer),
        sa.column("title", sa.String),
    )

    op.bulk_insert(
        input_type_table,
        [
            {"id": 1, "title": "content"},
            {"id": 2, "title": "text"},
            {"id": 3, "title": "description"},
            {"id": 4, "title": "number"},
            {"id": 5, "title": "reaction"},
            {"id": 6, "title": "multi-reaction"},
            {"id": 7, "title": "radio"},
            {"id": 8, "title": "multiple"},
            {"id": 9, "title": "file"},
            {"id": 10, "title": "image-file"},
            {"id": 11, "title": "header"},
            {"id": 12, "title": "chemicaldisposal"},
            {"id": 13, "title": "sortable-list"},
            {"id": 14, "title": "projectgroup-plan"},
            {"id": 15, "title": "projectgroup-hazard"},
            {"id": 16, "title": "yield"},
            {"id": 17, "title": "multi-yield"},
            {"id": 18, "title": "greenmetrics"},
            {"id": 19, "title": "multi-greenmetrics"},
            {"id": 20, "title": "datetime"},
            {"id": 21, "title": "formatted-text-input"},
        ],
    )

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("FieldResponseValue")
    op.drop_table("Comment")
    op.drop_table("SelectFieldOptions")
    op.drop_table("FieldResponse")
    op.drop_table("Field")
    op.drop_table("COSHHInstance")
    op.drop_table("TemplateInstance")
    op.drop_table("Section")
    op.drop_table("COSHHTemplate")
    op.drop_table("Template")
    op.drop_table("InputType")
    # ### end Alembic commands ###


def upgrade_update():
    pass


def downgrade_update():
    pass


def upgrade_audit_log():
    pass
    # ### end Alembic commands ###


def downgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
