"""add event time type message

Revision ID: 1702a83a51d7
Revises: e85106c37e48
Create Date: 2025-07-24 13:47:01.236456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1702a83a51d7'
down_revision = 'e85106c37e48'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuditLogEvent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('event_type', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuditLogEvent', schema=None) as batch_op:
        batch_op.drop_column('message')
        batch_op.drop_column('event_type')
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###

