"""subscription_tiers

Revision ID: 21cc6dce39da
Revises: 488aa917bf8c
Create Date: 2026-03-16 11:55:32.399864

"""
import sqlalchemy as sa
from alembic import op

subscription_tier = sa.Enum("FREE", "PRO", "ENTERPRISE", name="subscriptiontier")

# revision identifiers, used by Alembic.
revision = "21cc6dce39da"
down_revision = "488aa917bf8c"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the new enum type
    subscription_tier.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table("WorkGroup", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "subscription_tier",
                sa.Enum("FREE", "PRO", "ENTERPRISE", name="subscriptiontier"),
                server_default="ENTERPRISE",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("WorkGroup", schema=None) as batch_op:
        batch_op.drop_column("subscription_tier")

    # ### end Alembic commands ###


def upgrade_update():
    pass


def downgrade_update():
    pass


def upgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
