"""controlled_substances

Revision ID: 2e5d2071ac0b
Revises: f5b3539b9a0e
Create Date: 2025-03-03 13:40:50.405667

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e5d2071ac0b"
down_revision = "f5b3539b9a0e"
branch_labels = None
depends_on = None


def upgrade(engine_name: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controlled_substance_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator", sa.Integer(), nullable=False),
        sa.Column("workgroups", sa.Integer(), nullable=False),
        sa.Column("workbooks", sa.Integer(), nullable=False),
        sa.Column("reactions", sa.Integer(), nullable=False),
        sa.Column("time_of_creation", sa.DateTime(), nullable=True),
        sa.Column("last_edited", sa.DateTime(), nullable=True),
        sa.Column("last_location", sa.Text(), nullable=False),
        sa.Column("controlled_substance_name", sa.Text(), nullable=True),
        sa.Column("controlled_substance_smiles", sa.Text(), nullable=False),
        sa.Column("controlled_substance_cas", sa.Text(), nullable=True),
        sa.Column("controlled_substance_inchi", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["creator"], ["Person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reactions"], ["Reaction.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workbooks"], ["WorkBook.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workgroups"], ["WorkGroup.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade(engine_name: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("controlled_substance_usage")
    # ### end Alembic commands ###
