"""autogenerated_pdf_summary

Revision ID: 436a03e01053
Revises: 56de6fb3d672
Create Date: 2024-02-13 15:04:37.464177

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "436a03e01053"
down_revision = "56de6fb3d672"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ReactionDataFile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "autogenerated",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ReactionDataFile", schema=None) as batch_op:
        batch_op.drop_column("autogenerated")

    # ### end Alembic commands ###
