"""reaction_sets

Revision ID: 43a86ed23105
Revises: 488aa917bf8c
Create Date: 2025-08-12 15:36:54.635875

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "43a86ed23105"
down_revision = "488aa917bf8c"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ReactionSet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("time_of_creation", sa.DateTime(), nullable=False),
        sa.Column("time_of_update", sa.DateTime(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("reactor_dimensions", sa.JSON(), nullable=False),
        sa.Column("workbook_id", sa.Integer(), nullable=False),
        sa.Column("workgroup_id", sa.Integer(), nullable=False),
        sa.Column("complete", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("data_export_request_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["Person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["data_export_request_id"],
            ["DataExportRequest.id"],
        ),
        sa.ForeignKeyConstraint(["workbook_id"], ["WorkBook.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workgroup_id"], ["WorkGroup.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workbook_id", "name"),
        sa.UniqueConstraint("workbook_id", "set_id"),
    )
    with op.batch_alter_table("ReactionSet", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ReactionSet_creator_id"), ["creator_id"], unique=False
        )

    with op.batch_alter_table("Reaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reaction_set_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_reaction_reaction_set_id", "ReactionSet", ["reaction_set_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Reaction", schema=None) as batch_op:
        batch_op.drop_constraint("fk_reaction_reaction_set_id", type_="foreignkey")
        batch_op.drop_column("reaction_set_id")

    with op.batch_alter_table("ReactionSet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ReactionSet_creator_id"))

    op.drop_table("ReactionSet")
    # ### end Alembic commands ###


def upgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
