"""init_audit_log

Revision ID: 488aa917bf8c
Revises: e4ac09fbff85
Create Date: 2025-08-07 13:16:18.990945

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "488aa917bf8c"
down_revision = "e4ac09fbff85"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AuditLogEvent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("AuditLogEvent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_AuditLogEvent_event_time"), ["event_time"], unique=False
        )

    # ### end Alembic commands ###


def downgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("AuditLogEvent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_AuditLogEvent_event_time"))

    op.drop_table("AuditLogEvent")
    # ### end Alembic commands ###
