"""checksums

Revision ID: 56de6fb3d672
Revises: 65ddcc350a21
Create Date: 2024-02-09 14:31:38.556386

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56de6fb3d672"
down_revision = "65ddcc350a21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ReactionDataFile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sha256_checksum",
                sa.Text(),
                server_default="not_available",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ReactionDataFile", schema=None) as batch_op:
        batch_op.drop_column("sha256_checksum")

    # ### end Alembic commands ###
