"""data_export_request

Revision ID: 57cdfc52c9ed
Revises: c57d03c696a9
Create Date: 2024-04-24 13:46:55.135517

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57cdfc52c9ed"
down_revision = "c57d03c696a9"
branch_labels = None
depends_on = None


def upgrade(engine_name: str):
    if engine_name == "audit_log":
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DataExportRequest",
        sa.Column("time_of_request", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "data_format",
            sa.Enum(
                "RDF", "PDF", "ELN", "SURF", "CSV", "JSON", "SI", name="exportformat"
            ),
            nullable=True,
        ),
        sa.Column("requestor", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "APPROVED", "REJECTED", "EXPIRED", name="approvalstatus"
            ),
            nullable=True,
        ),
        sa.Column("uuid", sa.Text(), nullable=True),
        sa.Column("hash", sa.Text(), nullable=True),
        sa.Column("workgroup", sa.Integer(), nullable=False),
        sa.Column("institution", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution"], ["Institution.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["requestor"], ["Person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workgroup"], ["WorkGroup.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("DataExportRequest", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_DataExportRequest_institution"),
            ["institution"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_DataExportRequest_requestor"), ["requestor"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_DataExportRequest_workgroup"), ["workgroup"], unique=False
        )

    op.create_table(
        "data_export_request_approvers",
        sa.Column("data_export_request_id", sa.Integer(), nullable=True),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("responded", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_export_request_id"],
            ["DataExportRequest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["Person.id"],
        ),
    )
    op.create_table(
        "data_export_request_workbook_association",
        sa.Column("data_export_request_id", sa.Integer(), nullable=True),
        sa.Column("workbook_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_export_request_id"],
            ["DataExportRequest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workbook_id"],
            ["WorkBook.id"],
        ),
    )
    with op.batch_alter_table("Reaction", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("data_export_request_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_Reactions_data_export_request_ids_DataExportRequests",
            "DataExportRequest",
            ["data_export_request_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade(engine_name: str):
    if engine_name == "audit_log":
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Reaction", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_Reactions_data_export_request_ids_DataExportRequests",
            type_="foreignkey",
        )
        batch_op.drop_column("data_export_request_id")

    op.drop_table("data_export_request_workbook_association")
    op.drop_table("data_export_request_approvers")
    with op.batch_alter_table("DataExportRequest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_DataExportRequest_workgroup"))
        batch_op.drop_index(batch_op.f("ix_DataExportRequest_requestor"))
        batch_op.drop_index(batch_op.f("ix_DataExportRequest_institution"))

    op.drop_table("DataExportRequest")
    op.execute("DROP TYPE IF EXISTS approvalstatus;")
    op.execute("DROP TYPE IF EXISTS exportformat;")
    # ### end Alembic commands ###
