"""privacy_policy

Revision ID: 583f3c4423e8
Revises: 2e5d2071ac0b
Create Date: 2025-03-18 15:46:29.999502

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "583f3c4423e8"
down_revision = "2e5d2071ac0b"
branch_labels = None
depends_on = None


def upgrade(engine_name: str):
    if engine_name == "audit_log":
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("privacy_policy_accepted_on", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade(engine_name: str):
    if engine_name == "audit_log":
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.drop_column("privacy_policy_accepted_on")

    # ### end Alembic commands ###
