"""data-export-reactions

Revision ID: 5f8506546718
Revises: 57cdfc52c9ed
Create Date: 2024-06-25 09:51:31.495083

"""

from alembic import op
import sqlalchemy as sa

from migrations.utils import perform_migration


# revision identifiers, used by Alembic.
revision = "5f8506546718"
down_revision = "57cdfc52c9ed"
branch_labels = None
depends_on = None


def upgrade(engine_name: str):
    # test if the engine name is "default"
    if not perform_migration(engine_name):
        print(f"Not performing migration {__file__}")
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_export_request_reactions",
        sa.Column("data_export_request_id", sa.Integer(), nullable=True),
        sa.Column("reaction_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_export_request_id"],
            ["DataExportRequest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reaction_id"],
            ["Reaction.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_export_request_reactions")
    # ### end Alembic commands ###
