"""solvent_surfer

Revision ID: 65ddcc350a21
Revises: 330d1016bf41
Create Date: 2024-01-05 12:34:25.128664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65ddcc350a21'
down_revision = '330d1016bf41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PCA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('r_class', sa.Text(), nullable=False),
    sa.Column('colour_selected', sa.Text(), nullable=False),
    sa.Column('descriptors', sa.Text(), nullable=False),
    sa.Column('control_points', sa.JSON(), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=False),
    sa.Column('embedding_algorithm', sa.JSON(), nullable=False),
    sa.Column('time_of_creation', sa.DateTime(), nullable=False),
    sa.Column('time_of_update', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['Person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('PCA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PCA_creator'), ['creator'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('PCA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PCA_creator'))

    op.drop_table('PCA')
    # ### end Alembic commands ###
