"""index audit log time

Revision ID: 711d8fcaab4c
Revises: 1702a83a51d7
Create Date: 2025-07-24 13:50:46.370579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711d8fcaab4c'
down_revision = '1702a83a51d7'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuditLogEvent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AuditLogEvent_event_time'), ['event_time'], unique=False)

    # ### end Alembic commands ###


def downgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuditLogEvent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AuditLogEvent_event_time'))

    # ### end Alembic commands ###

