"""reaction_sets

Revision ID: 99d2e31970e9
Revises: fd539899cb90
Create Date: 2025-05-22 11:37:02.114194

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "99d2e31970e9"
down_revision = "fd539899cb90"
branch_labels = None
depends_on = None

# CHANGE THIS BEFORE PR - DOUBLE CHECK DOWN REVISION GOES TO MOST RECENT MIGRATION FROM MAIN BRANCH!!!!!!


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ReactionSet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("time_of_creation", sa.DateTime(), nullable=False),
        sa.Column("time_of_update", sa.DateTime(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("reactor_type", sa.Text(), nullable=False),
        sa.Column("workbook_id", sa.Integer(), nullable=False),
        sa.Column("complete", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("data_export_request_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["Person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["data_export_request_id"],
            ["DataExportRequest.id"],
        ),
        sa.ForeignKeyConstraint(["workbook_id"], ["WorkBook.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workbook_id", "name"),
        sa.UniqueConstraint("workbook_id", "set_id"),
    )
    with op.batch_alter_table("ReactionSet", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ReactionSet_creator_id"), ["creator_id"], unique=False
        )

    with op.batch_alter_table("Reaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reaction_set_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "ReactionSet", ["reaction_set_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Reaction", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("reaction_set_id")

    with op.batch_alter_table("ReactionSet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ReactionSet_creator_id"))

    op.drop_table("ReactionSet")
    # ### end Alembic commands ###
