"""retrosynthesis

Revision ID: a1c950d31d0e
Revises: 5f8506546718
Create Date: 2024-07-15 13:52:23.135520

"""

import sqlalchemy as sa
from alembic import op

from migrations.utils import perform_migration

# revision identifiers, used by Alembic.
revision = "a1c950d31d0e"
down_revision = "5f8506546718"
branch_labels = None
depends_on = None


def upgrade(engine_name: str):
    # test if the engine name is "default"
    if not perform_migration(engine_name):
        print(f"Not performing migration {__file__}")
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Retrosynthesis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("target_smiles", sa.Text(), nullable=False),
        sa.Column("creator", sa.Integer(), nullable=False),
        sa.Column("time_of_creation", sa.DateTime(), nullable=False),
        sa.Column("routes", sa.JSON(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("sustainability", sa.JSON(), nullable=True),
        sa.Column("uuid", sa.Text(), nullable=False),
        sa.Column("workbook", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["creator"], ["Person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workbook"], ["WorkBook.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workbook", "name"),
    )
    with op.batch_alter_table("Retrosynthesis", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_Retrosynthesis_creator"), ["creator"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Retrosynthesis", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_Retrosynthesis_creator"))

    op.drop_table("Retrosynthesis")
    # ### end Alembic commands ###
