"""init audit log db

Revision ID: a84dc8a36c6d
Revises: e4ac09fbff85
Create Date: 2025-07-23 13:57:53.462066

"""

from alembic import op
import sqlalchemy as sa

from migrations.utils import perform_migration


# revision identifiers, used by Alembic.
revision = "a84dc8a36c6d"
down_revision = "e4ac09fbff85"
branch_labels = None
depends_on = None


def upgrade(engine_name: str):
    # test if the engine name is "audit_log"
    if not perform_migration(engine_name, target="audit_log"):
        print(f"Not performing migration {__file__}")
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AuditLogEvent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("AuditLogEvent")
    # ### end Alembic commands ###
