"""Retrosynthesis access keys

Revision ID: aa00fe273863
Revises: 488aa917bf8c
Create Date: 2025-10-08 14:52:20.374604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa00fe273863'
down_revision = '488aa917bf8c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RetrosynthesisKey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RetrosynthesisKey')
    # ### end Alembic commands ###


def upgrade_update():
    pass


def downgrade_update():
    pass


def upgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

