"""empty message

Revision ID: ae1a2abe0374
Revises: 72a41927b677
Create Date: 2023-12-19 15:27:54.662603

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae1a2abe0374"
down_revision = "330d1016bf41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ReactionDataFile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sha256_checksum", sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ReactionDataFile", schema=None) as batch_op:
        batch_op.drop_column("sha256_checksum")

    # ### end Alembic commands ###
