"""controlled_substances

Revision ID: b8221f88c228
Revises: 70fd97efd6c4
Create Date: 2024-09-25 13:49:36.980129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8221f88c228'
down_revision = '70fd97efd6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlled_substance_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('workgroup', sa.Integer(), nullable=False),
    sa.Column('workbook', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.Integer(), nullable=False),
    sa.Column('date_used', sa.DateTime(), nullable=True),
    sa.Column('controlled_substance_name', sa.Text(), nullable=False),
    sa.Column('controlled_substance_smiles', sa.Text(), nullable=False),
    sa.Column('controlled_substance_cas', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['Person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction'], ['Reaction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workbook'], ['WorkBook.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workgroup'], ['WorkGroup.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_location', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('most_recent_login_location', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('most_recent_login_location')
        batch_op.drop_column('registration_location')

    op.drop_table('controlled_substance_usage')
    # ### end Alembic commands ###
