"""init audit log

Revision ID: e85106c37e48
Revises: e4ac09fbff85
Create Date: 2025-07-24 13:45:12.247101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85106c37e48'
down_revision = 'e4ac09fbff85'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditLogEvent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_audit_log():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AuditLogEvent')
    # ### end Alembic commands ###

