"""privacy_policy

Revision ID: ef1f62b26591
Revises: 2e5d2071ac0b
Create Date: 2025-03-18 13:39:31.071703

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef1f62b26591"
down_revision = "2e5d2071ac0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "privacy_policy_accepted_on",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.drop_column("privacy_policy_accepted_on")

    # ### end Alembic commands ###
