name: Deploy Audit Log Compressor to Azure

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Which environment to deploy'
        required: true
        type: choice
        options:
          - uat
          - prod


permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-uat:
    if: ${{ github.event.inputs.env == 'uat' }}
    runs-on: ubuntu-latest

    steps:
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-federated-identity: true

      - name: Restart container app with new image
        run: |
          az containerapp update \
            --name auditlogcompressoruat \
            --resource-group ${{ secrets.AZURE_RESOURCE_ID }} \
            --image ai4greeneln/audit_log_compressor:latest \
            --revision-suffix $GITHUB_RUN_NUMBER

  deploy-to-prod:
    if: ${{ github.event.inputs.env == 'prod' }}
    runs-on: ubuntu-latest

    steps:
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-federated-identity: true

      - name: Restart container app with new image
        run: |
          az containerapp update \
            --name auditlogcompressorprod \
            --resource-group ${{ secrets.AZURE_RESOURCE_ID }} \
            --image ai4greeneln/audit_log_compressor:latest \
            --revision-suffix $GITHUB_RUN_NUMBER
