name: Make Kafka Connect connectors for Audit Logs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  make-connectors:
    env:
      KAFKA_CONNECT_URL: ${{ secrets.KAFKA_CONNECT_URL }}
      MINIO_URL: ${{ secrets.MINIO_URL }}
      MINIO_BUCKET_NAME: ${{ secrets.MINIO_BUCKET_NAME }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      FLUSH_SIZE: 1

    runs-on: ubuntu-latest

    strategy:
      matrix:
        topic: ['reaction_edit_history', 'data_access_history']
        partition-fields: ['workgroup,date']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with: 
          python-version: 3.12

      - name: Istall project dependencies
        working-directory: microservices/kc_connector
        run: pip install .

      - name: Run connector script
        working-directory: microservices/kc_connector/src/kc_connector
        run: python . ${{ matric.topic }}
